version: "3.7"

networks:
  app:
    driver: bridge

volumes:
  app_db:

services:
  # Laravel application
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini # Override php.ini
    environment:
      DB_PORT: 3306
      DB_HOST: db
    networks:
      - app
    restart: unless-stopped
    tty: true
    depends_on:
      - server
      - db

  # NGINX Server
  server:
    image: nginx:1.25.3-alpine
    container_name: ${APP_NAME}-nginx
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - app
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal # this will be used when using phpstorm ide specific

  # MYSQL Database image
  db:
    image: mysql:8.3.0
    # build:
    #   context: ./.docker/mysql
    #   dockerfile: Dockerfile
    command: --default-authentication-plugin=caching_sha2_password
    container_name: ${APP_NAME}-db
    volumes:
      - ./.docker/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      - ./.docker/mysql:/etc/mysql/conf.d
      - app_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33061:3306"
    tty: true
    networks:
      - app

  # MYSQL Client adminer image
  adminer:
    image: adminer
    container_name: ${APP_NAME}-adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - app

  redis:
    container_name: ${APP_NAME}-redis
    image: redis:6.0
    ports:
      - 6379:6379
    networks:
      - app

  smtp:
    container_name: ${APP_NAME}-smtp
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - app
